Fix typo in CI message

diff --git a/.github/workflows/ci-workflow.yml b/.github/workflows/ci-workflow.yml
--- a/.github/workflows/ci-workflow.yml
+++ b/.github/workflows/ci-workflow.yml
@@ -15,7 +15,7 @@ jobs:
       - name: Check Format
         run: yarn format:check || echo "Ignore format error."
       - name: Run Linter
-        run: yarn lint || echo "Ignore format error."
+        run: yarn lint || echo "Ignore linter error."
       - name: Build
         run: yarn build
       - name: Upload Built Static Assets
